### ISSUE TITLE
Importing data on first run of the Windows application 

### ISSUE THREAD

**Issue by glocalglocal** [encryptic-team/encryptic#14]
I created an account on the web and Dropbox created the files structure. Then I installed Encrypt on Windows 10 64bit and on first run I tried to import the json file from Dropbox. Nothing happened, not even an error message was displayed. If I choose to create a new account from the Windows application, presumably my existing account will be overwritten. Not sure what I am supposed to do.

**Comment by daed** [comment]
The way you did it is the correct method.  That should probably be enhanced at some point in the future because it's not really obvious.

That's not good to hear though.  I've had success doing the import that way.  I didn't import from app to/from website, so maybe that's part of the issue.

**Comment by daed** [comment]
I found an issue with the import function.  I have it fixed in my code.  Will push shortly.  I can upload it to the website too but, I'm not going to have a release just yet.

Also, import looks like it expects a zip file from the full export.  I think there's a way to import just the profile in code, but it's not exposed to users, at least anywhere that I can see.  I'll see what I can do about that.  It would be neat to have it just work for either rather than the user needing to choose between two buttons.

**Comment by glocalglocal** [comment]
To clarify, I tried to use import as a way to get the Windows application to use the Dropbox file the web app used, ie to get them to sync. Isn't that how sync is supposed to be set up? I am wondering what happens if you use the two methods to access the file at the same time and generate a clash. This is probably another good reason to have auto-save and auto-backup.

**Comment by daed** [comment]
Yeah, that is how you're supposed to get the sync to work.

I'm not sure what happens if you step on the same files with a different account.  I don't think it will remove the files.  You won't be able to view your old files unless you import the first user's private key, but if you do that also?  Not sure.

I'll have a look and report back.  These are things worth having documented.
