### ISSUE TITLE
The desktop app is blinking from time to time during typing

### ISSUE THREAD

**Issue by hunterforcode** [encryptic-team/encryptic#15]
I am using 64Bit Ubuntu 18.04 and get the release version 0.0.1 here. 
https://github.com/encryptic-team/encryptic/releases

![illustration](https://i.imgur.com/s2rNAec.gif)
The gif taken from encryptic desktop app shows that the desktop app is blinking at times.
One blink moment in the gif is that the app blinks while I press enter below the word "well". 
Furthermore, you can see more blink moment if you are inputing more words. 

And the problem is gone in your web demo.
https://app.encryptic.org

**Comment by daed** [comment]
I suspect (especially since you can't replicate it in the web demo) that this is a issue with Electron/Ubuntu.

There's been a long-running Atom issue that is very similar.  Could you try the drirc workaround at https://github.com/atom/atom/issues/15323#issuecomment-427018396 and let me know if it fixes your issue?

**Comment by SeaLife** [comment]
Heyho, the web app is blinking too. If your typing and using a task list item and write, stop, wait, it should blink in a strange way on the right side. 

Regards
SeaLife

**Comment by yoyorast1** [comment]
I have the same issue. Using the windows app.

**Comment by daed** [comment]
Please let us know if this happens again on the latest version.
