### ISSUE TITLE
Importing data from laverna failed

### ISSUE THREAD

**Issue by greenpageantry** [encryptic-team/encryptic#29]
Hello Encryptic,

at first - thanks for giving Laverna a future, @daed! I really appreciate this and all the time that you put into it.

I was checking out the web app (it says Encryptic v0.0.2), created an identity and tried to import a fresh Laverna (original version, Beta v0.7.51) export (I have approx 100-200 notes in hierarchically ordered notebooks). I get an error message that the migration went wrong.

When navigating back to the "all notes" view, (which is only possible by using browser navigation and a new login), I can see that the names of the notes probably have been imported but when I click an arbitrary note, its content tries to load without any result being shown. When I browse to "Notebooks and Tags", there are no entries at all.

If I've got some spare time, I might try to fix that issue myself (although I'm quite new to GitHub and OSS contribution in general, but I know that it is probably complicated to debug this without having my Laverna export and I really like this project).

Does this behavior occur to anybody else?

**Comment by greenpageantry** [comment]
Okay, here is what I got so far analyzing this further:

It looks like my Laverna export contains .md files which are representation of each and every note in plain markup language. This stopped the whole import job in Import.js, with the return in line 372 (current master branch).

So what I tried is removing all these .md files which looked redundant and redo the import after wiping the account from my browser.

This time, I'm getting

Error: "Error encrypting message: Random number buffer depleted"
	onMessage https://app.encryptic.org/scripts/vendor.js:60848:19

**Comment by daed** [comment]
That's interesting.  I don't think we look the .md files.  I didn't think those were supposed to even be generated in laverna unless you disabled encryption, but I'd need to go back and look at the way that export works.  

That line is right in the middle of the openpgpjs library.  I'm surprised that even 200 notes could deplete their random number generator though.  I have 115 notes in my own backup and it worked for me last time I attempted the import, so I might be close to the threshold myself, if it is indeed note count related.

Can you tell me what your browser and OS are?  Also, since we encrypt notebooks and tags, they could be taxing it as well.  Can you get a total file count of what's in the backup zip?  If you're on linux or (I think it'll work) osx you can use ```find . | wc -l``` from a terminal in the laverna-backup directory and it'll give you a count.  In windows you can right click the folder and choose properties and it should give you a count there.  

I'm harder pressed for time this week than usual with the upcoming holiday, but I'll see what I can do.  I should at least be able to get some better logging in place.  Depending on what's going on, this might have to go back to the openpgpjs team.

**Comment by greenpageantry** [comment]
No problem if you need some more time, as I'm too quite busy and traveling without my private notebook where I've stored the exports at the moment.

I'm running Ubuntu 16.04 and probably used a current Firefox (or Chrome) for the export. Will let you know the the file count and more details once I'm back home.

**Comment by greenpageantry** [comment]
Okay here are all the details:
- Browser: Firefox 63.0.3 (64-bit)
- OS: Ubuntu 16.04
- Output of "find . | wc -l" (including the .md files): 550
- Output of "find . | wc -l" (without the .md files): 278 (looks like my guess of 100-200 notes was wrong)
- Backup archive structure (like tree would give it ;) ):
laverna-backups
|_ notes-db
....|_ configs.json
....|_ notebooks.json
....|_ tags.json
....|_ notes
........|_ 00079d14-449b-b60a-d113-b8fa74fc0c76.json
........|_ 00079d14-449b-b60a-d113-b8fa74fc0c76.md
........|_ 00905b5a-7c8a-f6ac-712b-38ef64baebee.json
........|_ 00905b5a-7c8a-f6ac-712b-38ef64baebee.md
........|_ ...

**Comment by daed** [comment]
Just wanted to put something out here to let you know that I haven't forgotten about this.  

I'm going to have a bit of time tonight.  I will make a bunch of notes up and give the import a shot.

**Comment by daed** [comment]
Well, months later, we've made some major improvements to the whole import process.

If you're still interested, could you try this with the new release?

**Comment by greenpageantry** [comment]
Hi @daed, no worries, I'm even later with this answer...
Thanks for the update. With the current version (v0.1.0) on app.encryptic.org, the import works just fine!
I am now having access to all the old notes in a maintained version of the app. Keep the good work going.
/Tobias
