### ISSUE TITLE
MathJax?

### ISSUE THREAD

**Issue by dayfuaim** [encryptic-team/encryptic#80]
Just executed https://app.encryptic.org.

I've created TEST Note and added simple MathJax markup: `$ \pi = -1 $`.
And I see it as is ("$ \pi = -1 $") instead of being rendered:
![Снимок экрана 2019-03-14 в 11 28 53](https://user-images.githubusercontent.com/1274699/54342003-6a83eb80-464c-11e9-857d-5f97be19f59b.png)

**Comment by dayfuaim** [comment]
**0.0.4** still has this issue.
Standalone build and web-app.

**Comment by Maks-s** [comment]
Hi 😺 
Sorry, MathJax isn't supported at the moment. We'll remove it from the list of features, and implement it later

**Comment by dayfuaim** [comment]
Understood.
Although it's expected from me to say "OK", I ask you:
_"Later is when?"_

Because MathJax (or KaTeX) is needed in Encryptic (and it was implemented in Laverna from the beginning).

**Comment by daed** [comment]
That's fair to ask.

So the reason we're so far behind is because we've been working off of the dev branch of laverna, not the master branch.  There were a couple different reasons I made that decision.  Old laverna was a dependency nightmare that required at least two different package managers (it might have been three), and at least one of those had been deprecated even back when v0.7.51 was new.  There were also some neat sounding new features in the dev branch, and in my starry-eyed naivety I thought it was a little bit more polished than it was.  Instead it was much less.  Put simply, a lot of what people think of as 'core' features of laverna weren't reimplemented in dev, which has been frustrating to catch up with as we're essentially reinventing the wheel.

On top of that, I've been in the process of working a day job, looking for a new day job, and moving halfway across the US, and more or less in that order.  So I've not had the amount of time to put into this that the project deserves, and that's no small amount of personal frustration to me.  And so that's why the project seems a little under-maintained.

Now, all that sounds like I'm leading up to this "I promise it'll happen one day" sob story, but the cool thing is that I actually had a few hours of undistributed productivity tonight and I think I figured this one out. :grin:   

Check it out:
![ArchLabs_2019-04-03-35_3840x1080](https://user-images.githubusercontent.com/1466660/55529263-1de96a00-5666-11e9-827f-35cdb556c050.png)

It's going to require a new release.  I'm not going to wait another month for that, but I would like a little more done before I put out another one, but in the meantime if you want to play with this, I'll get it put up on https://unstable.encryptic.org.

**Comment by daed** [comment]
@dayfuaim Feel free to reopen this or comment if desired.

**Comment by dayfuaim** [comment]
@daed Thanks a lot for your speed and quality!
Of course I'll see at https://unstable.encryptic.org.
And for sure I will test it for features it has and ones it should have (at least concerning KaTeX). :)

**Comment by dayfuaim** [comment]
I've checked what features of KaTeX current Unstable can and put here two screens.
This one is for reference (from another note-taking app Joplin):
![Снимок экрана 2019-04-04 в 11 26 04](https://user-images.githubusercontent.com/1274699/55541291-65efa780-56cd-11e9-96e2-f819f067a4ea.png)

And this – from current Unstable Encryptic:
![Снимок экрана 2019-04-04 в 11 26 24](https://user-images.githubusercontent.com/1274699/55541413-a5b68f00-56cd-11e9-80ed-0a4e65ffcb09.png)

I can guess the difference in rendering KaTeX is about fonts.

**Comment by daed** [comment]
Thanks for the testing!

The font thing is interesting.  I know that there's two different forms of output for the katex plugin.  One is mathml and the other is html.  The mathml one has the fancy fonts from your Joplin picture, but Firefox is the only browser that supports it right now, so I just went with the html output (which is significantly uglier) for greater compatibility.  It's better than nothing right now, but that's not going to work long-term, especially with the lack of sub/superscript.  

The interesting thing is that somehow Joplin is doing it, and I'm pretty sure it is Electron based. Maybe you're right and that extra font magic is a function of mathjax.  Maybe there's just something I'm missing.

**Comment by dayfuaim** [comment]
Yes, Joplin is Electron based.

BTW, I use Stylus extension for my browsers and included `@import url('https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.css');` (from https://katex.org) for https://*.encryptic.org. And we are almost there:
![Снимок экрана 2019-04-04 в 19 58 39](https://user-images.githubusercontent.com/1274699/55574054-1aacb780-5714-11e9-9d8c-e13e1ef491f3.png)
:)
Of course, it's accurate to style and rendering (symbols paddings and spaces).

**Comment by daed** [comment]
That looks like it was a big part of it, which makes sense.  I think @Maks-s saved the day in the PR he put out at #86 

I'll get it merged in a few hours after I get off work.  Based on the screencap in the PR I think this is in good shape.

**Comment by dayfuaim** [comment]
@daed @Maks-s Cool! :D

Could it be tested at https://unstable.encrypted.org?

**Comment by daed** [comment]
It should be live on unstable currently.  

At any rate, I'm glad you approve!

**Comment by dayfuaim** [comment]
@daed Yes, it lives there. :)

_But there are some issues:_

While loading/rendering note having `$...$`
![Снимок экрана 2019-04-05 в 17 44 31](https://user-images.githubusercontent.com/1274699/55636030-aed95600-57ca-11e9-9ada-db8e7fdf8b5c.png)
which gives this:
![Снимок экрана 2019-04-05 в 17 45 03](https://user-images.githubusercontent.com/1274699/55636096-d3cdc900-57ca-11e9-9b29-b9ed28efe841.png)

But locally (built from current `master`) everything's fine (in spite of lack of `*.woff2`):
![Снимок экрана 2019-04-05 в 17 52 38](https://user-images.githubusercontent.com/1274699/55636496-a9c8d680-57cb-11e9-8724-edd5099dfda4.png)

**Comment by Maks-s** [comment]
There must have been an error when the server copied the fonts. I did a PR (#87) to fix woff2 fonts, we'll see if it works after this

**Comment by daed** [comment]
Just eyeballing it, that seems like the culprit.

Timezones are against us, but I wish we could have these conversations when I wasn't at work.  :)

**Comment by dayfuaim** [comment]
@Maks-s @daed Very well done!
We are almost there! :)
Another small issue (https://unstable.encryptic.org):
![Снимок экрана 2019-04-08 в 14 24 57](https://user-images.githubusercontent.com/1274699/55720708-22b57180-5a0a-11e9-81b6-2865149dd89f.png)
(I have "Disabled Cache" in DevTools/Network)

Locally (built from current `master`) everything's fine.
